/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.ClienteDao;
import br.com.senac.dao.ClienteDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.ProfissaoDao;
import br.com.senac.dao.ProfissaoDaoImpl;
import br.com.senac.entidade.Cliente;
import br.com.senac.entidade.Endereco;
import br.com.senac.entidade.Profissao;
import br.com.senac.entidade.Telefone;
import br.com.senac.json.CepRest;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author jonathan.costa1
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    private Session sessao;
    private List<Profissao> profissoes;
    private ClienteDao clienteDao;
    private Cliente cliente;

    public CadastroCliente() {
        initComponents();
        carregarComboProfissao();
    }

    CadastroCliente(Cliente cliente) {
        initComponents();
        carregarComboProfissao();
        carregarAlteracaoPerfil(cliente);
        btSalvar.setText("Alterar");
        tituto_cadastro.setText("Alterar Cliente");
        setTitle("Alterar Cliente");
    }

    private void carregarAlteracaoPerfil(Cliente cliente) {
        this.cliente = cliente;
        varNome.setText(cliente.getNome());
        varCpf.setText(cliente.getCpf());
        varRg.setText(cliente.getRg());
        varSalario.setText(String.valueOf(cliente.getSalario()));

        varProfissao.getModel().setSelectedItem(cliente.getProfissao().getNome());

        varTelefone.setText(cliente.getTelefone().getNumero());
        varTipo.setText(cliente.getTelefone().getTipo());
        varOperadora.setText(cliente.getTelefone().getOperadora());
        varDdd.setText(cliente.getTelefone().getDdd());

        varCep.setText(cliente.getEndereco().getCep());
        varBairro.setText(cliente.getEndereco().getBairro());
        varCidade.setText(cliente.getEndereco().getLocalidade());
        varUf.setText(cliente.getEndereco().getUf());
        varObservacao.setText(cliente.getEndereco().getObservacao());
        varComplemento.setText(cliente.getEndereco().getComplemento());
        varEndereco.setText(cliente.getEndereco().getLogradouro());
        varNumero.setText(cliente.getEndereco().getNumero());

        btCancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_perfil4 = new javax.swing.JLabel();
        varLogin5 = new javax.swing.JTextField();
        tituto_cadastro = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_login = new javax.swing.JLabel();
        label_perfil = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        lb_perfil1 = new javax.swing.JLabel();
        varRg = new javax.swing.JTextField();
        varProfissao = new javax.swing.JComboBox<>();
        label_perfil1 = new javax.swing.JLabel();
        lb_perfil2 = new javax.swing.JLabel();
        lb_perfil3 = new javax.swing.JLabel();
        varOperadora = new javax.swing.JTextField();
        lb_perfil5 = new javax.swing.JLabel();
        varTipo = new javax.swing.JTextField();
        lb_perfil6 = new javax.swing.JLabel();
        lb_perfil7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_perfil8 = new javax.swing.JLabel();
        varEndereco = new javax.swing.JTextField();
        lb_perfil9 = new javax.swing.JLabel();
        varBairro = new javax.swing.JTextField();
        lb_perfil10 = new javax.swing.JLabel();
        varCidade = new javax.swing.JTextField();
        lb_perfil11 = new javax.swing.JLabel();
        varUf = new javax.swing.JTextField();
        lb_perfil12 = new javax.swing.JLabel();
        varNumero = new javax.swing.JTextField();
        lb_perfil13 = new javax.swing.JLabel();
        varComplemento = new javax.swing.JTextField();
        lb_perfil14 = new javax.swing.JLabel();
        varObservacao = new javax.swing.JTextField();
        varCpf = new javax.swing.JFormattedTextField();
        varSalario = new javax.swing.JFormattedTextField();
        varTelefone = new javax.swing.JFormattedTextField();
        varDdd = new javax.swing.JFormattedTextField();
        varCep = new javax.swing.JFormattedTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lb_perfil4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil4.setText("Salário:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");

        tituto_cadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituto_cadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituto_cadastro.setText("Cadastro Cliente");
        tituto_cadastro.setToolTipText("");

        label_nome.setText("Nome:");

        label_login.setText("CPF:");

        label_perfil.setText("RG:");

        varNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNomeActionPerformed(evt);
            }
        });

        btCancelar.setText("Limpar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lb_perfil1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil1.setText("Salário:");

        varProfissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um perfil..." }));
        varProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varProfissaoActionPerformed(evt);
            }
        });

        label_perfil1.setText("Profissao:");

        lb_perfil2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil2.setText("DDD:");

        lb_perfil3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil3.setText("Telefone:");

        lb_perfil5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil5.setText("Operadora:");

        lb_perfil6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil6.setText("Tipo:");

        lb_perfil7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil7.setText("CEP:");

        jButton1.setText("Buscar CEP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Contato");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Endereço");

        lb_perfil8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil8.setText("Endereço:");

        lb_perfil9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil9.setText("Bairro:");

        lb_perfil10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil10.setText("Cidade:");

        varCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCidadeActionPerformed(evt);
            }
        });

        lb_perfil11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil11.setText("UF:");

        lb_perfil12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil12.setText("Numero:");

        varNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNumeroActionPerformed(evt);
            }
        });

        lb_perfil13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil13.setText("Complemento:");

        lb_perfil14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_perfil14.setText("Observação:");

        try {
            varCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        varCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCpfActionPerformed(evt);
            }
        });

        varSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        varSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varSalarioActionPerformed(evt);
            }
        });

        try {
            varTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            varDdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            varCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_perfil2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lb_perfil3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(176, 176, 176))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(varTelefone))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(label_perfil)
                                            .addComponent(label_nome)
                                            .addComponent(label_login)
                                            .addComponent(lb_perfil1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(varNome)
                                            .addComponent(varRg, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                                            .addComponent(varCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(varProfissao, 0, 389, Short.MAX_VALUE)
                                            .addComponent(varSalario)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_perfil6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(varTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituto_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_perfil1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lb_perfil5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(varOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(199, 199, 199))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btCancelar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSalvar)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lb_perfil14)
                                                .addGap(12, 12, 12)
                                                .addComponent(varObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lb_perfil7)
                                                    .addComponent(lb_perfil8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(varEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lb_perfil9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lb_perfil13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(varComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lb_perfil12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lb_perfil11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lb_perfil10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(varCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituto_cadastro)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_login)
                    .addComponent(varCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_perfil)
                    .addComponent(varRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil1)
                    .addComponent(varSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_perfil1)
                    .addComponent(varProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil2)
                    .addComponent(lb_perfil3)
                    .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varDdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil5)
                    .addComponent(varOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_perfil6)
                    .addComponent(varTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil7)
                    .addComponent(jButton1)
                    .addComponent(varCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil8)
                    .addComponent(varEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil11)
                    .addComponent(varUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_perfil12)
                    .addComponent(varNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_perfil10)
                    .addComponent(varCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil9)
                    .addComponent(varBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_perfil13)
                    .addComponent(varComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_perfil14)
                    .addComponent(varObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        clienteDao = new ClienteDaoImpl();
        Telefone telefone = new Telefone();
        Endereco endereco = new Endereco();
        sessao = HibernateUtil.abrirConexao();
        if (validarFormulario()) {
            if (cliente == null) {
                cliente = new Cliente();
            }

            cliente.setNome(varNome.getText());
            cliente.setCpf((varCpf.getText().replace("-", "")).replace(".", ""));
            cliente.setRg(varRg.getText());
            cliente.setSalario(Double.valueOf(varSalario.getText().replace(",", ".")));
            int indice = varProfissao.getSelectedIndex();
            indice--;
            cliente.setProfissao(profissoes.get(indice));

            telefone.setNumero(varTelefone.getText());
            telefone.setDdd((varDdd.getText().replace("(", "")).replace(")", ""));
            telefone.setOperadora(varOperadora.getText());
            telefone.setTipo(varTipo.getText());
            cliente.setTelefone(telefone);

            endereco.setNumero(varNumero.getText());
            endereco.setComplemento(varComplemento.getText());
            endereco.setObservacao(varObservacao.getText());
            endereco.setBairro(varBairro.getText());
            endereco.setCep((varCep.getText().replace(".", "")).replace("-", ""));
            endereco.setLocalidade(varCidade.getText());
            endereco.setLogradouro(varEndereco.getText());
            endereco.setUf(varUf.getText());
            cliente.setEndereco(endereco);

            clienteDao.salvarOuAlterar(cliente, sessao);

            dispose();
            JOptionPane.showMessageDialog(null, "Usuário salvo com sucesso!");
            sessao.close();
        }
    }//GEN-LAST:event_btSalvarActionPerformed
    private boolean validarFormulario() {

        int indice = varProfissao.getSelectedIndex();
        String nome = varNome.getText().trim();
        String cpf = varCpf.getText().trim();
        String ddd = varDdd.getText().trim();
        System.out.println(ddd);

        if (validarCampoMenor3Caracter(nome)) {
            JOptionPane.showMessageDialog(null, "Preencha o nome corretamente");
            return false;
        }
        if (indice == 0) {
            JOptionPane.showMessageDialog(null, "Escolha uma profissao");
            return false;
        }
        if (varSalario == null || varSalario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o salário");
            return false;
        }
        if (varRg == null || varRg.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o RG");
            return false;
        }
        if (cpf == null || cpf.isEmpty() || (validarCampoMenor14Caracter(cpf))) {
            JOptionPane.showMessageDialog(null, "Digite o CPF");
            return false;
        }
        if (varTelefone == null || varTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um telefone");
            return false;
        }
        if (ddd == null || ddd.isEmpty() || (validarCampoMenor3Caracter(ddd)) || ddd.equals("(  )")) {
            JOptionPane.showMessageDialog(null, "Digite um DDD");
            return false;
        }
        if (varOperadora == null || varOperadora.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite uma Operadora");
            return false;
        }
        if (varTipo == null || varTipo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um Tipo");
            return false;
        }
        if (varCep == null || varCep.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite um CEP");
            return false;
        }
        return true; //retornar falso apenas explicação
    }

    private boolean validarCampoMenor3Caracter(String campo) {
        return campo.length() < 3;
    }

    private boolean validarCampoMenor14Caracter(String campo) {
        return campo.length() < 14;
    }
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        btCancelar.addActionListener((ActionEvent e) -> {
            varCpf.setText("");
            varNome.setText("");
            varDdd.setText("");
            varLogin5.setText("");
            varRg.setText("");
            varOperadora.setText("");
            varRg.setText("");
            varTelefone.setText("");
            varTipo.setText("");
        }
        );
    }//GEN-LAST:event_btCancelarActionPerformed

    private void carregarComboProfissao() {
        ProfissaoDao profissaoDao = new ProfissaoDaoImpl();
        try {
            sessao = HibernateUtil.abrirConexao();
            profissoes = profissaoDao.pesquisarTodos(sessao);
            profissoes.forEach(prof -> {
                varProfissao.addItem(prof.getNome());
            });
        } catch (HibernateException e) {
            System.out.println("erro ao pesquisar todas as profissoes" + e.getMessage());
        } finally {
            sessao.close();
        }
    }
    private void varProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varProfissaoActionPerformed

    private void varNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CepRest cepRest = new CepRest();
        Endereco endereco;
        if (varCep.getText().length() > 10 || varCep.getText().length() < 10) {
            JOptionPane.showMessageDialog(this, "Digite o CEP corretamente");
        } else {
            endereco = cepRest.pesquisaCep((varCep.getText().replace(".", "")).replace("-", ""));
            if (endereco.isErro()) {
                JOptionPane.showMessageDialog(this, "CEP incorreto, tente novamente");
            } else {
                varBairro.setText(endereco.getBairro());
                varEndereco.setText(endereco.getLogradouro());
                varCidade.setText(endereco.getLocalidade());
                varUf.setText(endereco.getUf());
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void varNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNumeroActionPerformed

    private void varCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varCidadeActionPerformed

    private void varCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varCpfActionPerformed

    private void varSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_perfil;
    private javax.swing.JLabel label_perfil1;
    private javax.swing.JLabel lb_perfil1;
    private javax.swing.JLabel lb_perfil10;
    private javax.swing.JLabel lb_perfil11;
    private javax.swing.JLabel lb_perfil12;
    private javax.swing.JLabel lb_perfil13;
    private javax.swing.JLabel lb_perfil14;
    private javax.swing.JLabel lb_perfil2;
    private javax.swing.JLabel lb_perfil3;
    private javax.swing.JLabel lb_perfil4;
    private javax.swing.JLabel lb_perfil5;
    private javax.swing.JLabel lb_perfil6;
    private javax.swing.JLabel lb_perfil7;
    private javax.swing.JLabel lb_perfil8;
    private javax.swing.JLabel lb_perfil9;
    private javax.swing.JLabel tituto_cadastro;
    private javax.swing.JTextField varBairro;
    private javax.swing.JFormattedTextField varCep;
    private javax.swing.JTextField varCidade;
    private javax.swing.JTextField varComplemento;
    private javax.swing.JFormattedTextField varCpf;
    private javax.swing.JFormattedTextField varDdd;
    private javax.swing.JTextField varEndereco;
    private javax.swing.JTextField varLogin5;
    private javax.swing.JTextField varNome;
    private javax.swing.JTextField varNumero;
    private javax.swing.JTextField varObservacao;
    private javax.swing.JTextField varOperadora;
    private javax.swing.JComboBox<String> varProfissao;
    private javax.swing.JTextField varRg;
    private javax.swing.JFormattedTextField varSalario;
    private javax.swing.JFormattedTextField varTelefone;
    private javax.swing.JTextField varTipo;
    private javax.swing.JTextField varUf;
    // End of variables declaration//GEN-END:variables

}
